url: https://www.windowwalker.com
baseurl: 

# Site settings
title: Window Walker
email: betsegaw.ta@gmail.com
description: "Window walker is an app that lets you search and switch between windows that you have open, all from the comfort of your keyboard. As you are searching for an app, you can use the keyboard up and down arrows to see an Alt-Tab style preview of the windows."


# Team names, titles and social links
people:
- name: Betsegaw Tadele
  pic: 1
  position: Software Developer
  social:
    - title: twitter
      url: https://twitter.com/betsegaw

# Build settings
markdown: kramdown
permalink: pretty